# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
# org.gradle.configuration-cache=true

# Mod properties
mod.version=5.4.1
mod.group=net.quantumaidan.itemLore
mod.id=itemlore
mod.name=ItemLore

# Global dependencies
deps.fabric_loader=0.17.3

publish.modrinth=ZXr70n5I
publish.curseforge=1134622

# Version specific properties for 26.1.2
deps.minecraft=26.1.2
deps.fabric_api=0.150.0+26.1.2
deps.midnightlib=1.9.3+26.1-fabric
deps.modmenu=18.0.0-alpha.8
# deps.sgtveinminer=3.0.3+1.21.10

# Minecraft dependency for fabric.mod.json
mod.mc_dep==26.1.2

# Release title for Modrinth and Curseforge
mod.mc_title=26.1.2

# Space-separated compatible versions for publishing
mod.mc_targets=26.1.2
