deps.fabric_api=0.116.7+1.21.1
# Minecraft dependency for fabric.mod.json
mod.mc_dep=1.21.1

# Release title for Modrinth and Curseforge
mod.mc_title=1.21.1

# Space-separated compatible versions for publishing
mod.mc_targets=1.21.1

## Dependencies (checked seperately) 12/15/2025
# >>> https://www.midnightdust.eu/wiki/midnightlib/
deps.midnightlib = 1.9.2+1.21.1-fabric
# >>> https://modrinth.com/mod/modmenu/versions
deps.modmenu=11.0.3
deps.sgtveinminer=3.0.3+1.21.1